name: Test Cpp

on:
  push:
    paths:
      - 'Cpp/**'
      - '.github/workflows/Cpp.yml'
  pull_request:
    paths:
      - 'Cpp/**'
      - '.github/workflows/Cpp.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Build
      working-directory: Cpp
      run: make compileTest

    - name: Test
      working-directory: Cpp
      run: make runTest
